CREATE TABLE `ship` (
	`id`	INTEGER NOT NULL,
	`number`	INTEGER,
	`name_kanji`	TEXT,
	`name`	TEXT,
	`suffix`	INTEGER,
	`fire`	INTEGER,
	`fire_max`	INTEGER,
	`torpedo`	INTEGER,
	`torpedo_max`	INTEGER,
	`aa`	INTEGER,
	`aa_max`	INTEGER,
	`asw`	INTEGER,
	`asw_max`	INTEGER,
	`hp`	INTEGER,
	`hp_max`	INTEGER,
	`armor`	INTEGER,
	`armor_max`	INTEGER,
	`evasion`	INTEGER,
	`evasion_max`	INTEGER,
	`carry`	INTEGER,
	`speed`	INTEGER,
	`range`	INTEGER,
	`los`	INTEGER,
	`los_max`	INTEGER,
	`luck`	INTEGER,
	`luck_max`	INTEGER,
	PRIMARY KEY(id)
)
